# Generated by Django 5.1.6 on 2025-04-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module')),
            ],
        ),
    ]
