# Generated by Django 5.1.6 on 2025-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text_material', models.TextField()),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course_videos')),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('course_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
