# Generated by Django 5.1.6 on 2025-03-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateCourse',
            new_name='Content',
        ),
    ]
