# Generated by Django 5.1.6 on 2025-03-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_module_delete_content_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to='module_image'),
        ),
    ]
