# Generated by Django 5.1.6 on 2025-03-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='module_number',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_description',
            new_name='module_title',
        ),
    ]
